BEGIN;
--
-- Create model Article
--
CREATE TABLE "blog_article" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "title" varchar(200) NOT NULL, "content" text NOT NULL, "vote" integer NOT NULL, "date_created" timestamp with time zone NOT NULL, "author_id" bigint NOT NULL);
--
-- Create model Comment
--
CREATE TABLE "blog_comment" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "content" text NOT NULL, "vote" integer NOT NULL, "article_id" bigint NOT NULL, "user_id" bigint NOT NULL);
--
-- Create model Blog
--
CREATE TABLE "blog_blog" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "article_id" bigint NOT NULL);
ALTER TABLE "blog_article" ADD CONSTRAINT "blog_article_author_id_905add38_fk_users_customuser_id" FOREIGN KEY ("author_id") REFERENCES "users_customuser" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "blog_article_author_id_905add38" ON "blog_article" ("author_id");
ALTER TABLE "blog_comment" ADD CONSTRAINT "blog_comment_article_id_3d58bca6_fk_blog_article_id" FOREIGN KEY ("article_id") REFERENCES "blog_article" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "blog_comment" ADD CONSTRAINT "blog_comment_user_id_59a54155_fk_users_customuser_id" FOREIGN KEY ("user_id") REFERENCES "users_customuser" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "blog_comment_article_id_3d58bca6" ON "blog_comment" ("article_id");
CREATE INDEX "blog_comment_user_id_59a54155" ON "blog_comment" ("user_id");
ALTER TABLE "blog_blog" ADD CONSTRAINT "blog_blog_article_id_34d84312_fk_blog_article_id" FOREIGN KEY ("article_id") REFERENCES "blog_article" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "blog_blog_article_id_34d84312" ON "blog_blog" ("article_id");
COMMIT;
