# Generated by Django 4.2.5 on 2023-09-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_comment_content_alter_comment_vote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
